-- MySQL Script generated by MySQL Workbench
-- Wed Aug 28 12:29:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema challengedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema challengedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `challengedb` DEFAULT CHARACTER SET utf8 ;
USE `challengedb` ;

-- -----------------------------------------------------
-- Table `challengedb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengedb`.`status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `challengedb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengedb`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `challengedb`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengedb`.`task` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  `description` TEXT NOT NULL,
  `user_id` INT(11) NOT NULL,
  `status_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_task_status1_idx` (`status_id` ASC),
  INDEX `fk_task_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_task_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `challengedb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `challengedb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `challengedb`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `challengedb`;
INSERT INTO `challengedb`.`status` (`id`, `name`) VALUES (DEFAULT, 'Pendiente');
INSERT INTO `challengedb`.`status` (`id`, `name`) VALUES (DEFAULT, 'En progreso');
INSERT INTO `challengedb`.`status` (`id`, `name`) VALUES (DEFAULT, 'Completada');

COMMIT;

