-- MySQL Script generated by MySQL Workbench
-- Mon Aug 26 16:37:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema challengedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema challengedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `challengedb` DEFAULT CHARACTER SET utf8 ;
USE `challengedb` ;

-- -----------------------------------------------------
-- Table `challengedb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengedb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challengedb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengedb`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challengedb`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengedb`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  `description` TEXT NOT NULL,
  `status_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT now(),
  `updated_at` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_task_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_task_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `challengedb`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `challengedb`.`users_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `challengedb`.`users_tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_task_user_idx` (`user_id` ASC),
  INDEX `fk_user_task_task1_idx` (`task_id` ASC),
  CONSTRAINT `fk_user_task_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `challengedb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_task_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `challengedb`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `challengedb`.`status`
-- -----------------------------------------------------
START TRANSACTION;
USE `challengedb`;
INSERT INTO `challengedb`.`status` (`id`, `name`) VALUES (DEFAULT, 'pendiente');
INSERT INTO `challengedb`.`status` (`id`, `name`) VALUES (DEFAULT, 'en progreso');
INSERT INTO `challengedb`.`status` (`id`, `name`) VALUES (DEFAULT, 'completada');

COMMIT;

